name: "Enforce pull request title"

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  enforce-pr-title:
    runs-on: ubuntu-latest
    steps:
    - uses: deepakputhraya/action-pr-title@master
      with:
        regex: '\w+: .+' # Regex the title should match.
        allowed_prefixes: 'fix,feat,chore,ci,docs,style,Release,refactor,perf,test' # title should start with the given prefix
        prefix_case_sensitive: false # title prefix are case insensitive
        min_length: 10 # Min length of the title
        github_token: ${{ github.token }} # Default: ${{ github.token }}
